name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - 'infra/*'
      - '.github/*'
     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: 100180/redditclone
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
