apiVersion: v1
kind: Service
metadata:
  name: {{ include "reddit-clone.fullname" . }}
  labels:
    {{- include "reddit-clone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodeport: {{ .Values.service.nodeport }}
  selector:
    {{- include "reddit-clone.selectorLabels" . | nindent 4 }}
